[2025-02-05 04:19:20,429: INFO: main: Welocme to the Project:]
[2025-02-07 04:44:59,316: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-07 04:44:59,317: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-07 04:45:37,332: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-07 04:45:37,335: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-07 04:45:37,336: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-07 04:45:37,337: INFO: common:  directory artifacts created:]
[2025-02-07 04:45:37,339: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-07 04:55:07,406: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-07 04:55:07,408: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-07 04:55:44,705: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-07 04:55:44,707: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-07 04:55:44,709: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-07 04:55:44,711: INFO: common:  directory artifacts created:]
[2025-02-07 04:55:44,712: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-07 04:57:56,307: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-07 04:57:56,309: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-07 04:57:56,311: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-07 04:57:56,312: INFO: common:  directory artifacts created:]
[2025-02-07 04:57:56,313: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-07 04:57:57,284: INFO: 1014596764: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 264426
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: text/plain; charset=utf-8
ETag: "9a924888464fdcd2f774fd1d2e6f01946afefdebfff9b88fc2f6045920f1a81b"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: FEB8:167B43:28992A:3A2B3A:67A5457B
Accept-Ranges: bytes
Date: Thu, 06 Feb 2025 23:27:57 GMT
Via: 1.1 varnish
X-Served-By: cache-del21724-DEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1738884477.861638,VS0,VE291
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 2869a7dd6f99a5ca5f0b23814f77379503d5b7ab
Expires: Thu, 06 Feb 2025 23:32:57 GMT
Source-Age: 0

:]
[2025-02-07 05:01:24,096: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-07 05:01:24,098: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-07 05:01:24,100: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-07 05:01:24,101: INFO: common:  directory artifacts created:]
[2025-02-07 05:01:24,102: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-07 05:01:24,103: INFO: 1014596764: File already exists:]
[2025-02-07 05:01:57,172: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-07 05:01:57,174: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-07 05:01:57,175: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-07 05:01:57,176: INFO: common:  directory artifacts created:]
[2025-02-07 05:01:57,177: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-07 05:01:59,081: INFO: 1014596764: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 4922:2C81D6:117E99:17E31B:67A5466E
Accept-Ranges: bytes
Date: Thu, 06 Feb 2025 23:31:58 GMT
Via: 1.1 varnish
X-Served-By: cache-del21740-DEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1738884718.467644,VS0,VE495
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 28ef99cc3265899b20e3fcef31bd951a2da071fd
Expires: Thu, 06 Feb 2025 23:36:58 GMT
Source-Age: 0

:]
[2025-02-07 16:46:32,439: INFO: main: Welocme to the Project:]
[2025-02-07 16:46:32,440: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-07 16:46:32,453: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-07 16:46:32,467: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-07 16:46:32,470: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-07 16:46:32,471: INFO: common:  directory artifacts created:]
[2025-02-07 16:46:32,473: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-07 16:46:32,474: ERROR: main: 'DataIngestionConfig' object has no attribute 'source_URL':]
Traceback (most recent call last):
  File "C:\Users\t0263519\Desktop\Study\PYTHON\MLFLOW-Projects\DataScienceProject-1\main.py", line 9, in <module>
    data_ingestion.initiate_data_ingestion()
  File "C:\Users\t0263519\Desktop\Study\PYTHON\MLFLOW-Projects\DataScienceProject-1\src\DataScience\pipeline\data_ingestion_pipeline.py", line 16, in initiate_data_ingestion
    data_ingestion.download_file()
  File "C:\Users\t0263519\Desktop\Study\PYTHON\MLFLOW-Projects\DataScienceProject-1\src\DataScience\components\data_ingestion.py", line 18, in download_file
    url = self.config.source_URL,
AttributeError: 'DataIngestionConfig' object has no attribute 'source_URL'
[2025-02-07 16:47:20,934: INFO: main: Welocme to the Project:]
[2025-02-07 16:47:20,935: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-07 16:47:20,937: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-07 16:47:20,938: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-07 16:47:20,939: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-07 16:47:20,940: INFO: common:  directory artifacts created:]
[2025-02-07 16:47:20,942: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-07 16:47:23,402: INFO: data_ingestion: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 23329
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "c69888a4ae59bc5a893392785a938ccd4937981c06ba8a9d6a21aa52b4ab5b6e"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: FA75:0883:2DD68F:3FCF86:67A5EBC2
Accept-Ranges: bytes
Date: Fri, 07 Feb 2025 11:17:23 GMT
Via: 1.1 varnish
X-Served-By: cache-del21721-DEL
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1738927043.957240,VS0,VE327
Vary: Authorization,Accept-Encoding,Origin
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 9acdc65faa2d5ceb339d988969522e6ee591a42d
Expires: Fri, 07 Feb 2025 11:22:23 GMT
Source-Age: 0

:]
[2025-02-07 16:47:23,422: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-10 12:18:44,050: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 12:18:44,064: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 12:18:44,077: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 12:18:44,080: INFO: common:  directory artifacts created:]
[2025-02-10 12:18:44,082: INFO: common:  directory artifacts/data_validation created:]
[2025-02-10 12:19:43,509: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 12:19:43,510: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 12:19:43,514: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 12:19:43,516: INFO: common:  directory artifacts created:]
[2025-02-10 12:19:43,518: INFO: common:  directory artifacts/data_validation created:]
[2025-02-10 12:32:23,865: INFO: main: Welocme to the Project:]
[2025-02-10 12:32:23,865: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-10 12:32:23,867: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 12:32:23,869: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 12:32:23,871: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 12:32:23,872: INFO: common:  directory artifacts created:]
[2025-02-10 12:32:23,872: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-10 12:32:23,873: INFO: data_ingestion: File already exists:]
[2025-02-10 12:32:23,892: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-10 12:32:23,892: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-10 12:32:23,894: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 12:32:23,895: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 12:32:23,897: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 12:32:23,897: INFO: common:  directory artifacts created:]
[2025-02-10 12:32:23,899: INFO: common:  directory artifacts/data_validation created:]
[2025-02-10 12:32:23,922: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-10 16:00:16,862: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:00:16,875: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:00:16,894: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:00:16,897: INFO: common:  directory artifacts created:]
[2025-02-10 16:00:16,900: INFO: common:  directory artifacts/data_transformation created:]
[2025-02-10 16:00:16,960: INFO: 2494119004: data splitted into train and test:]
[2025-02-10 16:00:16,962: INFO: 2494119004: (1199, 12):]
[2025-02-10 16:00:16,963: INFO: 2494119004: (400, 12):]
[2025-02-10 16:13:15,390: INFO: main: Welocme to the Project:]
[2025-02-10 16:13:15,391: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-10 16:13:15,405: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:13:15,422: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:13:15,434: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:13:15,435: INFO: common:  directory artifacts created:]
[2025-02-10 16:13:15,437: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-10 16:13:15,438: INFO: data_ingestion: File already exists:]
[2025-02-10 16:13:15,468: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-10 16:13:15,470: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-10 16:13:15,473: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:13:15,475: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:13:15,480: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:13:15,482: INFO: common:  directory artifacts created:]
[2025-02-10 16:13:15,482: INFO: common:  directory artifacts/data_validation created:]
[2025-02-10 16:13:15,513: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-10 16:13:15,514: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<:]
[2025-02-10 16:13:15,515: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x:]
[2025-02-10 16:13:58,793: INFO: main: Welocme to the Project:]
[2025-02-10 16:13:58,793: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-10 16:13:58,797: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:13:58,798: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:13:58,800: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:13:58,802: INFO: common:  directory artifacts created:]
[2025-02-10 16:13:58,804: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-10 16:13:58,804: INFO: data_ingestion: File already exists:]
[2025-02-10 16:13:58,813: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-10 16:13:58,814: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-10 16:13:58,822: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:13:58,824: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:13:58,828: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:13:58,830: INFO: common:  directory artifacts created:]
[2025-02-10 16:13:58,832: INFO: common:  directory artifacts/data_validation created:]
[2025-02-10 16:13:58,874: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-10 16:13:58,875: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<:]
[2025-02-10 16:13:58,895: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x:]
[2025-02-10 16:14:30,232: INFO: main: Welocme to the Project:]
[2025-02-10 16:14:30,232: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-10 16:14:30,236: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:14:30,237: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:14:30,240: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:14:30,241: INFO: common:  directory artifacts created:]
[2025-02-10 16:14:30,243: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-10 16:14:30,244: INFO: data_ingestion: File already exists:]
[2025-02-10 16:14:30,253: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-10 16:14:30,254: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-10 16:14:30,258: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:14:30,260: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:14:30,263: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:14:30,265: INFO: common:  directory artifacts created:]
[2025-02-10 16:14:30,267: INFO: common:  directory artifacts/data_validation created:]
[2025-02-10 16:14:30,300: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-10 16:14:30,301: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<:]
[2025-02-10 16:14:30,307: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:14:30,308: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:14:30,312: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:14:30,313: INFO: common:  directory artifacts created:]
[2025-02-10 16:14:30,315: INFO: common:  directory artifacts/data_transformation created:]
[2025-02-10 16:14:30,355: INFO: data_transformation: data splitted into train and test:]
[2025-02-10 16:14:30,355: INFO: data_transformation: (1199, 12):]
[2025-02-10 16:14:30,356: INFO: data_transformation: (400, 12):]
[2025-02-10 16:14:30,357: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x:]
[2025-02-10 16:39:36,072: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:39:36,085: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:39:36,097: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:39:36,099: INFO: common:  directory artifacts created:]
[2025-02-10 16:42:20,808: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:42:20,811: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:42:20,815: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:42:20,817: INFO: common:  directory artifacts created:]
[2025-02-10 16:42:20,821: INFO: common:  directory artifacts/model_trainer created:]
[2025-02-10 16:44:04,162: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 16:44:04,165: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 16:44:04,170: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 16:44:04,173: INFO: common:  directory artifacts created:]
[2025-02-10 16:44:04,175: INFO: common:  directory artifacts/model_trainer created:]
[2025-02-10 18:47:11,498: INFO: main: Welocme to the Project:]
[2025-02-10 18:47:11,499: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-10 18:47:11,518: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 18:47:11,533: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 18:47:11,548: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 18:47:11,550: INFO: common:  directory artifacts created:]
[2025-02-10 18:47:11,551: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-10 18:47:11,552: INFO: data_ingestion: File already exists:]
[2025-02-10 18:47:11,578: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-10 18:47:11,579: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-10 18:47:11,583: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 18:47:11,584: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 18:47:11,586: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 18:47:11,587: INFO: common:  directory artifacts created:]
[2025-02-10 18:47:11,588: INFO: common:  directory artifacts/data_validation created:]
[2025-02-10 18:47:11,623: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-10 18:47:11,625: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<:]
[2025-02-10 18:47:11,639: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 18:47:11,643: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 18:47:11,645: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 18:47:11,648: INFO: common:  directory artifacts created:]
[2025-02-10 18:47:11,648: INFO: common:  directory artifacts/data_transformation created:]
[2025-02-10 18:47:11,679: INFO: data_transformation: data splitted into train and test:]
[2025-02-10 18:47:11,680: INFO: data_transformation: (1199, 12):]
[2025-02-10 18:47:11,681: INFO: data_transformation: (400, 12):]
[2025-02-10 18:47:11,682: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x:]
[2025-02-10 18:47:11,683: INFO: main: >>>>>> stage Model Training Stage started <<<<<<:]
[2025-02-10 18:47:11,688: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-10 18:47:11,689: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-10 18:47:11,691: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-10 18:47:11,692: INFO: common:  directory artifacts created:]
[2025-02-10 18:47:11,694: INFO: common:  directory artifacts/model_trainer created:]
[2025-02-10 18:47:11,741: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x:]
[2025-02-11 04:30:39,070: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 04:30:39,082: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 04:30:39,090: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 04:30:39,092: INFO: common:  directory artifacts created:]
[2025-02-11 04:30:39,093: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 04:32:54,569: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 04:32:54,572: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 04:32:54,575: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 04:32:54,576: INFO: common:  directory artifacts created:]
[2025-02-11 04:32:54,577: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 04:32:55,093: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:32:59,194: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:33:07,747: WARNING: connectionpool: Retrying (Retry(total=4, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:33:24,272: WARNING: connectionpool: Retrying (Retry(total=3, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:33:56,622: WARNING: connectionpool: Retrying (Retry(total=2, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:35:01,542: WARNING: connectionpool: Retrying (Retry(total=1, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:36:44,711: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 04:36:44,714: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 04:36:44,717: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 04:36:44,719: INFO: common:  directory artifacts created:]
[2025-02-11 04:36:44,720: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 04:36:45,409: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:36:49,742: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:36:58,657: WARNING: connectionpool: Retrying (Retry(total=4, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:37:14,785: WARNING: connectionpool: Retrying (Retry(total=3, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:37:47,885: WARNING: connectionpool: Retrying (Retry(total=2, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:38:52,782: WARNING: connectionpool: Retrying (Retry(total=1, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:54:10,077: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 04:54:10,087: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 04:54:10,097: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 04:54:10,098: INFO: common:  directory artifacts created:]
[2025-02-11 04:54:10,100: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 04:54:10,906: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:54:15,268: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:55:19,460: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 04:55:19,462: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 04:55:19,464: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 04:55:19,465: INFO: common:  directory artifacts created:]
[2025-02-11 04:55:19,466: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 04:55:19,807: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:55:24,571: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:55:33,098: WARNING: connectionpool: Retrying (Retry(total=4, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:55:49,715: WARNING: connectionpool: Retrying (Retry(total=3, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 04:56:21,865: WARNING: connectionpool: Retrying (Retry(total=2, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:07:48,955: INFO: main: Welocme to the Project:]
[2025-02-11 05:07:48,956: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-11 05:07:48,959: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:07:48,972: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:07:48,983: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:07:48,984: INFO: common:  directory artifacts created:]
[2025-02-11 05:07:48,984: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-11 05:07:48,985: INFO: data_ingestion: File already exists:]
[2025-02-11 05:07:48,999: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-11 05:07:49,001: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-11 05:07:49,004: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:07:49,005: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:07:49,006: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:07:49,007: INFO: common:  directory artifacts created:]
[2025-02-11 05:07:49,008: INFO: common:  directory artifacts/data_validation created:]
[2025-02-11 05:07:49,027: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-11 05:07:49,028: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<:]
[2025-02-11 05:07:49,040: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:07:49,041: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:07:49,043: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:07:49,044: INFO: common:  directory artifacts created:]
[2025-02-11 05:07:49,045: INFO: common:  directory artifacts/data_transformation created:]
[2025-02-11 05:07:49,065: INFO: data_transformation: data splitted into train and test:]
[2025-02-11 05:07:49,066: INFO: data_transformation: (1199, 12):]
[2025-02-11 05:07:49,066: INFO: data_transformation: (400, 12):]
[2025-02-11 05:07:49,067: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x:]
[2025-02-11 05:07:49,067: INFO: main: >>>>>> stage Model Training Stage started <<<<<<:]
[2025-02-11 05:07:49,070: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:07:49,071: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:07:49,073: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:07:49,074: INFO: common:  directory artifacts created:]
[2025-02-11 05:07:49,074: INFO: common:  directory artifacts/model_trainer created:]
[2025-02-11 05:07:49,122: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x:]
[2025-02-11 05:07:49,122: ERROR: main: name 'STAGE' is not defined:]
Traceback (most recent call last):
  File "C:\Users\t0263519\Desktop\Study\PYTHON\MLFLOW-Projects\DataScienceProject-1\main.py", line 53, in <module>
    logger.info(f">>>>>> stage {STAGE} started <<<<<<")
NameError: name 'STAGE' is not defined
[2025-02-11 05:08:08,752: INFO: main: Welocme to the Project:]
[2025-02-11 05:08:08,753: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-11 05:08:08,755: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:08:08,756: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:08:08,758: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:08:08,759: INFO: common:  directory artifacts created:]
[2025-02-11 05:08:08,760: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-11 05:08:08,761: INFO: data_ingestion: File already exists:]
[2025-02-11 05:08:08,766: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-11 05:08:08,767: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-11 05:08:08,770: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:08:08,771: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:08:08,772: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:08:08,773: INFO: common:  directory artifacts created:]
[2025-02-11 05:08:08,773: INFO: common:  directory artifacts/data_validation created:]
[2025-02-11 05:08:08,790: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-11 05:08:08,791: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<:]
[2025-02-11 05:08:08,795: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:08:08,796: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:08:08,797: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:08:08,798: INFO: common:  directory artifacts created:]
[2025-02-11 05:08:08,798: INFO: common:  directory artifacts/data_transformation created:]
[2025-02-11 05:08:08,812: INFO: data_transformation: data splitted into train and test:]
[2025-02-11 05:08:08,813: INFO: data_transformation: (1199, 12):]
[2025-02-11 05:08:08,813: INFO: data_transformation: (400, 12):]
[2025-02-11 05:08:08,813: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x:]
[2025-02-11 05:08:08,814: INFO: main: >>>>>> stage Model Training Stage started <<<<<<:]
[2025-02-11 05:08:08,817: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:08:08,818: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:08:08,819: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:08:08,820: INFO: common:  directory artifacts created:]
[2025-02-11 05:08:08,820: INFO: common:  directory artifacts/model_trainer created:]
[2025-02-11 05:08:08,852: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x:]
[2025-02-11 05:08:08,853: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<:]
[2025-02-11 05:08:08,855: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:08:08,857: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:08:08,858: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:08:08,859: INFO: common:  directory artifacts created:]
[2025-02-11 05:08:08,862: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:08:08,863: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:08:08,864: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:08:08,865: INFO: common:  directory artifacts created:]
[2025-02-11 05:08:08,866: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 05:08:09,676: ERROR: main: [Errno 2] No such file or directory: 'artifacts\\model_evaluation\\metrics.json':]
Traceback (most recent call last):
  File "C:\Users\t0263519\Desktop\Study\PYTHON\MLFLOW-Projects\DataScienceProject-1\main.py", line 55, in <module>
    obj.initiate_model_evaluation()
  File "C:\Users\t0263519\Desktop\Study\PYTHON\MLFLOW-Projects\DataScienceProject-1\src\DataScience\pipeline\model_evaluation_pipeline.py", line 17, in initiate_model_evaluation
    model_evaluation.log_into_mlflow()
  File "C:\Users\t0263519\Desktop\Study\PYTHON\MLFLOW-Projects\DataScienceProject-1\src\DataScience\components\model_evaluation.py", line 44, in log_into_mlflow
    save_json(path=Path(self.config.metric_file_name), data=scores)
  File "C:\Users\t0263519\Desktop\Study\PYTHON\MLFLOW-Projects\DataScienceProject-1\venv\lib\site-packages\ensure\main.py", line 835, in __call__
    return self.f(*args, **kwargs)
  File "C:\Users\t0263519\Desktop\Study\PYTHON\MLFLOW-Projects\DataScienceProject-1\src\DataScience\utils\common.py", line 33, in save_json
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\model_evaluation\\metrics.json'
[2025-02-11 05:15:45,476: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:15:45,484: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:15:45,492: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:15:45,494: INFO: common:  directory artifacts created:]
[2025-02-11 05:15:45,495: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 05:15:45,899: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:15:50,703: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:15:59,272: WARNING: connectionpool: Retrying (Retry(total=4, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:16:49,113: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:16:49,115: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:16:49,118: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:16:49,119: INFO: common:  directory artifacts created:]
[2025-02-11 05:16:49,120: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 05:16:49,447: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:16:53,950: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:17:34,535: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:17:34,537: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:17:34,540: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:17:34,541: INFO: common:  directory artifacts created:]
[2025-02-11 05:17:34,542: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 05:17:34,621: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:17:39,346: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:25:36,643: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:25:36,645: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:25:36,648: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:25:36,649: INFO: common:  directory artifacts created:]
[2025-02-11 05:25:36,650: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 05:25:37,008: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:25:41,222: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:25:49,576: WARNING: connectionpool: Retrying (Retry(total=4, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:26:55,610: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:26:55,611: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:26:55,614: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:26:55,616: INFO: common:  directory artifacts created:]
[2025-02-11 05:26:55,617: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 05:26:55,716: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:26:59,874: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:28:54,430: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:28:54,433: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:28:54,436: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:28:54,438: INFO: common:  directory artifacts created:]
[2025-02-11 05:28:54,439: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 05:28:54,524: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:28:58,833: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:33:23,364: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 05:33:23,366: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 05:33:23,368: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 05:33:23,369: INFO: common:  directory artifacts created:]
[2025-02-11 05:33:23,370: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 05:33:23,759: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 05:33:28,052: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 10:06:38,912: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 10:06:38,914: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 10:06:38,918: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 10:06:38,919: INFO: common:  directory artifacts created:]
[2025-02-11 10:06:38,920: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 10:06:39,674: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 10:06:43,903: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 10:06:52,081: WARNING: connectionpool: Retrying (Retry(total=4, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 10:07:09,098: WARNING: connectionpool: Retrying (Retry(total=3, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 10:11:45,349: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 10:11:45,359: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 10:11:45,371: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 10:11:45,372: INFO: common:  directory artifacts created:]
[2025-02-11 10:11:45,373: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 10:13:19,678: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 10:13:19,680: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 10:13:19,682: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 10:13:19,683: INFO: common:  directory artifacts created:]
[2025-02-11 10:13:19,685: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:31:27,174: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:31:27,186: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:31:27,197: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:31:27,198: INFO: common:  directory artifacts created:]
[2025-02-11 11:31:27,199: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:35:00,710: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:35:00,712: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:35:00,714: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:35:00,715: INFO: common:  directory artifacts created:]
[2025-02-11 11:35:00,716: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:40:32,891: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:40:32,905: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:40:32,920: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:40:32,922: INFO: common:  directory artifacts created:]
[2025-02-11 11:40:32,924: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:44:12,169: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:44:12,171: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:44:12,174: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:44:12,176: INFO: common:  directory artifacts created:]
[2025-02-11 11:44:12,177: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:44:55,150: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:44:55,152: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:44:55,154: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:44:55,156: INFO: common:  directory artifacts created:]
[2025-02-11 11:44:55,157: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:45:14,744: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:45:14,746: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:45:14,748: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:45:14,750: INFO: common:  directory artifacts created:]
[2025-02-11 11:45:14,751: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:45:15,118: INFO: common: json file saved at artifacts\model_evaluation\metrics.json:]
[2025-02-11 11:46:44,441: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:46:44,443: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:46:44,445: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:46:44,447: INFO: common:  directory artifacts created:]
[2025-02-11 11:46:44,448: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:46:44,512: INFO: common: json file saved at artifacts\model_evaluation\metrics.json:]
[2025-02-11 11:52:19,978: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:52:19,980: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:52:19,983: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:52:19,984: INFO: common:  directory artifacts created:]
[2025-02-11 11:52:19,985: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:52:20,046: INFO: common: json file saved at artifacts\model_evaluation\metrics.json:]
[2025-02-11 11:52:49,224: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:52:49,226: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:52:49,230: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:52:49,232: INFO: common:  directory artifacts created:]
[2025-02-11 11:52:49,234: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:52:49,307: INFO: common: json file saved at artifacts\model_evaluation\metrics.json:]
[2025-02-11 11:56:14,225: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:56:14,241: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:56:14,255: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:56:14,256: INFO: common:  directory artifacts created:]
[2025-02-11 11:56:14,258: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:56:14,378: INFO: common: json file saved at artifacts\model_evaluation\metrics.json:]
[2025-02-11 11:58:17,527: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 11:58:17,529: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 11:58:17,532: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 11:58:17,533: INFO: common:  directory artifacts created:]
[2025-02-11 11:58:17,534: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 11:58:18,292: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 11:58:23,237: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 11:58:32,114: WARNING: connectionpool: Retrying (Retry(total=4, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 11:58:49,165: WARNING: connectionpool: Retrying (Retry(total=3, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 11:59:22,245: WARNING: connectionpool: Retrying (Retry(total=2, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 12:01:09,186: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 12:01:09,189: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 12:01:09,192: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 12:01:09,194: INFO: common:  directory artifacts created:]
[2025-02-11 12:01:09,195: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 12:01:09,639: WARNING: connectionpool: Retrying (Retry(total=6, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 12:01:14,662: WARNING: connectionpool: Retrying (Retry(total=5, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 12:01:23,743: WARNING: connectionpool: Retrying (Retry(total=4, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 12:01:40,630: WARNING: connectionpool: Retrying (Retry(total=3, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 12:02:13,279: WARNING: connectionpool: Retrying (Retry(total=2, connect=7, read=7, redirect=7, status=7)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /sahilsiddharth/DataScienceProject.mlflow/api/2.0/mlflow/runs/create:]
[2025-02-11 12:04:20,868: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 12:04:20,869: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 12:04:20,872: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 12:04:20,873: INFO: common:  directory artifacts created:]
[2025-02-11 12:04:20,874: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 12:04:23,234: WARNING: connectionpool: Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024DEE4EB130>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create:]
[2025-02-11 12:04:29,629: WARNING: connectionpool: Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024DEE4EAD10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create:]
[2025-02-11 12:04:40,650: WARNING: connectionpool: Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024DEE524BB0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create:]
[2025-02-11 12:04:59,109: WARNING: connectionpool: Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024DEE5244F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create:]
[2025-02-11 12:04:59,198: INFO: common: json file saved at artifacts\model_evaluation\metrics.json:]
[2025-02-11 12:08:20,325: INFO: main: Welocme to the Project:]
[2025-02-11 12:08:20,326: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-11 12:08:20,328: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 12:08:20,329: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 12:08:20,330: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 12:08:20,331: INFO: common:  directory artifacts created:]
[2025-02-11 12:08:20,331: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-11 12:08:20,332: INFO: data_ingestion: File already exists:]
[2025-02-11 12:08:20,350: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-11 12:08:20,351: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-11 12:08:20,354: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 12:08:20,355: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 12:08:20,357: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 12:08:20,358: INFO: common:  directory artifacts created:]
[2025-02-11 12:08:20,358: INFO: common:  directory artifacts/data_validation created:]
[2025-02-11 12:08:20,377: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-11 12:08:20,377: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<:]
[2025-02-11 12:08:20,390: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 12:08:20,391: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 12:08:20,393: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 12:08:20,394: INFO: common:  directory artifacts created:]
[2025-02-11 12:08:20,394: INFO: common:  directory artifacts/data_transformation created:]
[2025-02-11 12:08:20,412: INFO: data_transformation: data splitted into train and test:]
[2025-02-11 12:08:20,413: INFO: data_transformation: (1199, 12):]
[2025-02-11 12:08:20,413: INFO: data_transformation: (400, 12):]
[2025-02-11 12:08:20,413: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x:]
[2025-02-11 12:08:20,413: INFO: main: >>>>>> stage Model Training Stage started <<<<<<:]
[2025-02-11 12:08:20,416: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 12:08:20,417: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 12:08:20,419: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 12:08:20,420: INFO: common:  directory artifacts created:]
[2025-02-11 12:08:20,420: INFO: common:  directory artifacts/model_trainer created:]
[2025-02-11 12:08:20,466: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x:]
[2025-02-11 12:08:20,467: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<:]
[2025-02-11 12:08:20,470: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 12:08:20,471: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 12:08:20,473: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 12:08:20,473: INFO: common:  directory artifacts created:]
[2025-02-11 12:08:20,476: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 12:08:20,477: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 12:08:20,478: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 12:08:20,479: INFO: common:  directory artifacts created:]
[2025-02-11 12:08:20,479: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 12:08:21,278: INFO: common: json file saved at artifacts\model_evaluation\metrics.json:]
[2025-02-11 12:08:28,525: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x==========x:]
[2025-02-11 16:09:15,732: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.42.73.80:8080:]
[2025-02-11 16:09:15,733: INFO: _internal: [33mPress CTRL+C to quit[0m:]
[2025-02-11 16:09:29,481: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.42.73.80:8080:]
[2025-02-11 16:09:29,481: INFO: _internal: [33mPress CTRL+C to quit[0m:]
[2025-02-11 16:09:33,459: INFO: _internal: 127.0.0.1 - - [11/Feb/2025 16:09:33] "GET / HTTP/1.1" 200 -:]
[2025-02-11 16:09:33,503: INFO: _internal: 127.0.0.1 - - [11/Feb/2025 16:09:33] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -:]
[2025-02-11 16:09:33,519: INFO: _internal: 127.0.0.1 - - [11/Feb/2025 16:09:33] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -:]
[2025-02-11 16:10:45,440: INFO: main: Welocme to the Project:]
[2025-02-11 16:10:45,441: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-11 16:10:45,454: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:10:45,468: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:10:45,479: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:10:45,480: INFO: common:  directory artifacts created:]
[2025-02-11 16:10:45,481: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-11 16:10:45,481: INFO: data_ingestion: File already exists:]
[2025-02-11 16:10:45,498: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-11 16:10:45,498: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-11 16:10:45,502: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:10:45,503: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:10:45,505: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:10:45,506: INFO: common:  directory artifacts created:]
[2025-02-11 16:10:45,507: INFO: common:  directory artifacts/data_validation created:]
[2025-02-11 16:10:45,536: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-11 16:10:45,537: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<:]
[2025-02-11 16:10:45,553: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:10:45,555: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:10:45,558: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:10:45,559: INFO: common:  directory artifacts created:]
[2025-02-11 16:10:45,560: INFO: common:  directory artifacts/data_transformation created:]
[2025-02-11 16:10:45,582: INFO: data_transformation: data splitted into train and test:]
[2025-02-11 16:10:45,583: INFO: data_transformation: (1199, 12):]
[2025-02-11 16:10:45,583: INFO: data_transformation: (400, 12):]
[2025-02-11 16:10:45,584: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x:]
[2025-02-11 16:10:45,584: INFO: main: >>>>>> stage Model Training Stage started <<<<<<:]
[2025-02-11 16:10:45,587: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:10:45,589: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:10:45,590: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:10:45,591: INFO: common:  directory artifacts created:]
[2025-02-11 16:10:45,592: INFO: common:  directory artifacts/model_trainer created:]
[2025-02-11 16:10:45,632: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x:]
[2025-02-11 16:10:45,632: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<:]
[2025-02-11 16:10:45,638: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:10:45,640: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:10:45,642: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:10:45,643: INFO: common:  directory artifacts created:]
[2025-02-11 16:10:45,645: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:10:45,647: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:10:45,649: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:10:45,650: INFO: common:  directory artifacts created:]
[2025-02-11 16:10:45,651: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 16:10:48,628: WARNING: connectionpool: Retrying (Retry(total=6, connect=6, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DD7F4CB580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create:]
[2025-02-11 16:10:55,374: WARNING: connectionpool: Retrying (Retry(total=5, connect=5, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DD7F4CB400>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create:]
[2025-02-11 16:11:05,742: WARNING: connectionpool: Retrying (Retry(total=4, connect=4, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DD7F4CACE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create:]
[2025-02-11 16:11:23,971: WARNING: connectionpool: Retrying (Retry(total=3, connect=3, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DD7F4CAE90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create:]
[2025-02-11 16:11:58,546: WARNING: connectionpool: Retrying (Retry(total=2, connect=2, read=7, redirect=7, status=7)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002DD7F4CAA40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /api/2.0/mlflow/runs/create:]
[2025-02-11 16:12:43,915: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.42.73.80:8080:]
[2025-02-11 16:12:43,916: INFO: _internal: [33mPress CTRL+C to quit[0m:]
[2025-02-11 16:12:53,125: INFO: main: Welocme to the Project:]
[2025-02-11 16:12:53,125: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-11 16:12:53,128: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:12:53,129: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:12:53,131: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:12:53,132: INFO: common:  directory artifacts created:]
[2025-02-11 16:12:53,133: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-11 16:12:53,133: INFO: data_ingestion: File already exists:]
[2025-02-11 16:12:53,137: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-11 16:12:53,138: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-11 16:12:53,142: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:12:53,142: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:12:53,144: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:12:53,145: INFO: common:  directory artifacts created:]
[2025-02-11 16:12:53,146: INFO: common:  directory artifacts/data_validation created:]
[2025-02-11 16:12:53,169: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-11 16:12:53,170: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<:]
[2025-02-11 16:12:53,175: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:12:53,176: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:12:53,178: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:12:53,179: INFO: common:  directory artifacts created:]
[2025-02-11 16:12:53,179: INFO: common:  directory artifacts/data_transformation created:]
[2025-02-11 16:12:53,194: INFO: data_transformation: data splitted into train and test:]
[2025-02-11 16:12:53,195: INFO: data_transformation: (1199, 12):]
[2025-02-11 16:12:53,195: INFO: data_transformation: (400, 12):]
[2025-02-11 16:12:53,196: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x:]
[2025-02-11 16:12:53,196: INFO: main: >>>>>> stage Model Training Stage started <<<<<<:]
[2025-02-11 16:12:53,199: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:12:53,200: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:12:53,202: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:12:53,202: INFO: common:  directory artifacts created:]
[2025-02-11 16:12:53,203: INFO: common:  directory artifacts/model_trainer created:]
[2025-02-11 16:12:53,237: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x:]
[2025-02-11 16:12:53,239: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<:]
[2025-02-11 16:12:53,243: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:12:53,244: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:12:53,246: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:12:53,246: INFO: common:  directory artifacts created:]
[2025-02-11 16:12:53,249: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-11 16:12:53,250: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-11 16:12:53,252: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-11 16:12:53,252: INFO: common:  directory artifacts created:]
[2025-02-11 16:12:53,254: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-11 16:12:54,311: INFO: common: json file saved at artifacts\model_evaluation\metrics.json:]
[2025-02-11 16:13:04,737: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x==========x:]
[2025-02-11 16:13:05,099: INFO: _internal: 127.0.0.1 - - [11/Feb/2025 16:13:05] "GET /train HTTP/1.1" 200 -:]
[2025-02-11 16:13:49,936: INFO: _internal: 127.0.0.1 - - [11/Feb/2025 16:13:49] "GET / HTTP/1.1" 200 -:]
[2025-02-11 16:13:49,958: INFO: _internal: 127.0.0.1 - - [11/Feb/2025 16:13:49] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -:]
[2025-02-11 16:14:08,491: INFO: _internal: 127.0.0.1 - - [11/Feb/2025 16:14:08] "POST /predict HTTP/1.1" 200 -:]
[2025-02-11 16:15:12,125: INFO: _internal: 127.0.0.1 - - [11/Feb/2025 16:15:12] "POST /predict HTTP/1.1" 200 -:]
[2025-02-11 16:15:17,786: INFO: _internal: 127.0.0.1 - - [11/Feb/2025 16:15:17] "POST /predict HTTP/1.1" 200 -:]
[2025-02-11 16:15:29,354: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.42.73.80:8080:]
[2025-02-11 16:15:29,356: INFO: _internal: [33mPress CTRL+C to quit[0m:]
[2025-02-11 16:15:40,525: INFO: _internal: 127.0.0.1 - - [11/Feb/2025 16:15:40] "POST /predict HTTP/1.1" 200 -:]
[2025-02-12 19:31:00,343: INFO: _internal: [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.29.102:8080:]
[2025-02-12 19:31:00,344: INFO: _internal: [33mPress CTRL+C to quit[0m:]
[2025-02-12 19:31:13,058: INFO: _internal: 127.0.0.1 - - [12/Feb/2025 19:31:13] "GET / HTTP/1.1" 200 -:]
[2025-02-12 19:31:13,096: INFO: _internal: 127.0.0.1 - - [12/Feb/2025 19:31:13] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -:]
[2025-02-12 19:31:24,590: INFO: main: Welocme to the Project:]
[2025-02-12 19:31:24,590: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-02-12 19:31:24,603: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-12 19:31:24,616: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-12 19:31:24,631: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-12 19:31:24,632: INFO: common:  directory artifacts created:]
[2025-02-12 19:31:24,634: INFO: common:  directory artifacts/data_ingestion created:]
[2025-02-12 19:31:24,634: INFO: data_ingestion: File already exists:]
[2025-02-12 19:31:24,653: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-02-12 19:31:24,653: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-02-12 19:31:24,656: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-12 19:31:24,658: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-12 19:31:24,660: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-12 19:31:24,660: INFO: common:  directory artifacts created:]
[2025-02-12 19:31:24,661: INFO: common:  directory artifacts/data_validation created:]
[2025-02-12 19:31:24,689: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
[2025-02-12 19:31:24,689: INFO: main: >>>>>> stage Data Transformation stage started <<<<<<:]
[2025-02-12 19:31:24,701: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-12 19:31:24,703: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-12 19:31:24,705: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-12 19:31:24,706: INFO: common:  directory artifacts created:]
[2025-02-12 19:31:24,706: INFO: common:  directory artifacts/data_transformation created:]
[2025-02-12 19:31:24,728: INFO: data_transformation: data splitted into train and test:]
[2025-02-12 19:31:24,729: INFO: data_transformation: (1199, 12):]
[2025-02-12 19:31:24,730: INFO: data_transformation: (400, 12):]
[2025-02-12 19:31:24,730: INFO: main: >>>>>> stage Data Transformation stage completed <<<<<<

x==========x:]
[2025-02-12 19:31:24,730: INFO: main: >>>>>> stage Model Training Stage started <<<<<<:]
[2025-02-12 19:31:24,733: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-12 19:31:24,734: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-12 19:31:24,735: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-12 19:31:24,736: INFO: common:  directory artifacts created:]
[2025-02-12 19:31:24,737: INFO: common:  directory artifacts/model_trainer created:]
[2025-02-12 19:31:24,780: INFO: main: >>>>>> stage Model Training Stage completed <<<<<<

x==========x:]
[2025-02-12 19:31:24,780: INFO: main: >>>>>> stage Model Evaluation Stage started <<<<<<:]
[2025-02-12 19:31:24,783: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-12 19:31:24,784: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-12 19:31:24,785: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-12 19:31:24,786: INFO: common:  directory artifacts created:]
[2025-02-12 19:31:24,789: INFO: common: yaml file config\config.yaml loaded successfully:]
[2025-02-12 19:31:24,790: INFO: common: yaml file params.yaml loaded successfully:]
[2025-02-12 19:31:24,791: INFO: common: yaml file schema.yaml loaded successfully:]
[2025-02-12 19:31:24,792: INFO: common:  directory artifacts created:]
[2025-02-12 19:31:24,793: INFO: common:  directory artifacts/model_evaluation created:]
[2025-02-12 19:31:25,996: INFO: common: json file saved at artifacts\model_evaluation\metrics.json:]
[2025-02-12 19:31:35,492: INFO: main: >>>>>> stage Model Evaluation Stage completed <<<<<<

x==========x:]
[2025-02-12 19:31:35,893: INFO: _internal: 127.0.0.1 - - [12/Feb/2025 19:31:35] "GET /train HTTP/1.1" 200 -:]
[2025-02-12 19:32:15,083: INFO: _internal: 127.0.0.1 - - [12/Feb/2025 19:32:15] "GET / HTTP/1.1" 200 -:]
[2025-02-12 19:32:15,100: INFO: _internal: 127.0.0.1 - - [12/Feb/2025 19:32:15] "[33mGET /static/assets/img/form-v9.jpg HTTP/1.1[0m" 404 -:]
[2025-02-12 19:32:52,270: INFO: _internal: 127.0.0.1 - - [12/Feb/2025 19:32:52] "POST /predict HTTP/1.1" 200 -:]
